### ISSUE TITLE
Determine necessary links to be launched using the script

### ISSUE THREAD

**Issue by ghost** [johnthetacoman/threat-investigator#1]
The script will utilize multiple sites to check for recent malicious activity in order to determine if the IP Address/Domain/URL is a threat. @johnthetacoman is going to create a list of the utilized sites.

**Comment by johnthetacoman** [comment]
@daneedore these are the link we need to launch using this script:
•	https://www.abuseipdb.com/
•	https://talosintelligence.com/
•	https://www.virustotal.com/gui/home/upload
•	https://www.malwareurl.com/listing-urls.php
•	https://www.brightcloud.com/tools/url-ip-lookup.php
•	https://www.shodan.io/
•	https://fortiguard.com/webfilter?q=winbricks.co.zw&version=8
•	https://www.ipvoid.com/
•	https://centralops.net/co/DomainDossier.aspx
•	https://viewdns.info/
