### ISSUE TITLE
Implement user input functionality for IP addresses

### ISSUE THREAD

**Issue by johnthetacoman** [johnthetacoman/threat-investigator#4]
@daneedore and I need to make the script accept user input for IP addresses, and be able to insert the IP addresses on the corresponding sites' forums.

**Comment by johnthetacoman** [comment]
I created the initial functionality for IP address input in commit #24e2778. @daneedore please add the additional requirements to allow for the use of an IP address to be passed as a command line argument. In addition, please test for this IP address input feature before merging with the production branch.

**Comment by ghost** [comment]
I rewrote the program to utilize command line arguments. It works, and in future versions of the script, we will add exception handling and write unit tests before merging with the production branch.
